#####################################################
#                  Test automations
#####################################################
- alias: 'Test notification'
  hide_entity: false
  trigger:
    platform: numeric_state
    entity_id: sensor.random_sensor
    above: 20  # Max=20
  action:
    service: persistent_notification.create
    data:
      title: "A notification appeared!"
      message: "Here is a message"

- alias: 'Test tts' # doesnt work
  hide_entity: false
  trigger:
    platform: numeric_state
    entity_id: sensor.random_sensor
    above: 20  # Max=20
  action:
    service: tts.google_say
    entity_id: media_player.mpd
    data:
      message: 'Go to bed now'
      
# - alias: 'Test mp3' # doesnt work
#   hide_entity: false
#   trigger:
#     platform: time
#     at: '22:50:00'
#   action:
#     service: media_player.play_media
#     data:
#       entity_id: media_player.mpd
#       media_content_id: 'https://hassio.local:8123/local/01_oevningskoera-cia.mp3'
#       media_content_type: 'music'

# - alias: 'Test Spotify'
#   hide_entity: false
#   trigger:
#     platform: time
#     at: '23:15:00'
#   action:
#     service: media_player.play_media
#     data:
#       entity_id: media_player.spotify
#       media_content_id: 'spotify:user:spotify:playlist:37i9dQZF1DX2MyUCsl25eb' # Morning Commute
#       media_content_type: 'playlist'


#####################################################
#              HA startup actions
#####################################################
- alias: 'Set theme at startup'
  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: default
    - delay:
        seconds: 20
    - service: automation.turn_on
      entity_id: automation.enter

#####################################################
#                 Come-and-go
#####################################################
- alias: 'Enter'
  hide_entity: false
  initial_state: false
  trigger:
    platform: state
    entity_id: group.any_device
    to: 'home'
  condition:
    condition: time
    after: '14:00:00'
    before: '23:00:00'
  action:
    - service: script.turn_on_lights
    - service: script.prepare_hassio_music
    - service: media_player.play_media
      data:
        entity_id: media_player.spotify
        media_content_id: 'spotify:user:spotify:playlist:37i9dQZF1DX7K31D69s4M1' # Piano in the background
        media_content_type: 'playlist'

- alias: 'Exit'
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.any_device
    to: 'not_home'
  action:
    - service: light.turn_off
      data:
        entity_id: group.lights
    - service: media_player.media_pause
      entity_id: media_player.spotify

- alias: 'Arrival Bunny'
  hide_entity: false
  trigger:
    platform: state
    entity_id: sensor.device_oneplus7
    to: 'home'
  condition:
    condition: time
    after: '09:00:00'
    before: '23:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.mpd
        volume_level: '0.5'
    - service: tts.google_say
      data_template:
        message: >
          {{ states.sensor.human1.state }} har kommit hem!
        language: 'sv'

- alias: 'Arrival Koala'
  hide_entity: false
  trigger:
    platform: state
    entity_id: sensor.device_honor_10
    to: 'home'
  condition:
    condition: time
    after: '09:00:00'
    before: '23:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.mpd
        volume_level: '0.5'
    - service: tts.google_say
      data_template:
        message: >
          {{ states.sensor.human2.state }} har kommit hem!
        language: 'sv'

#####################################################
#                 Lights
#####################################################
- alias: 'Sunset lights'
  hide_entity: false
  trigger:
    platform: sun
    event: 'sunset'
    offset: '-00:30:00'
  condition:
    condition: state
    entity_id: group.any_device
    state: 'home'
  action:
    service: light.turn_on
    data:
        entity_id: light.vardagsrum
        brightness: 255
        kelvin: 3400
        transition: 2

- alias: 'Evening lights'
  hide_entity: false
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    - condition: state
      entity_id: group.all_lights
      state: 'on'
    - condition: numeric_state
      entity_id: light.vardagsrum
      value_template: '{% if states.light.vardagsrum.state == "on"  %}{{ states.light.vardagsrum.attributes.brightness }}{% else %}0{% endif %}'
      above: 150
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: 'Late evening lights'
  hide_entity: false
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    - condition: state
      entity_id: group.all_lights
      state: 'on'
    - condition: numeric_state
      entity_id: light.vardagsrum
      value_template: '{% if states.light.vardagsrum.state == "on"  %}{{ states.light.vardagsrum.attributes.brightness }}{% else %}0{% endif %}'
      above: 150
  action:
    service: scene.turn_on
    entity_id: scene.late_evening

- alias: 'Turn off lights'
  hide_entity: false
  trigger:
    - platform: time
      at: '23:59:59'
  condition:
    condition: state
    entity_id: group.all_lights
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.night

#####################################################
#                  Wake up
#####################################################
- alias: 'Good morning'
  hide_entity: false
  initial_state: 'off'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.any_device
      state: home
  action:
    service: tts.google_say
    data_template:
      message: >
        'Dags att gå upp. Klockan är {{ now().hour }} {{ now().minute }}'
      language: 'sv'

#####################################################
#                  Go to bed
#####################################################
#- alias: 'Good night'
#  hide_entity: false
#  trigger:
#    platform: time
#    at: '23:00:00'
#  action:
#    service: light.turn_on
#    entity_id: light.bedroom
#    data:
#      transition: 900

#####################################################
#                   Spotify
#####################################################
- alias: 'Set Spotify Volume'
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state  }}'
