homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30.25
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# HTTP
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:
  reporting: false

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: random
#  - platform: sl
#    name: home
#    ri4key: !secret trafiklab_ri4key
#    si2key: !secret trafiklab_si2key
#    siteid: 9204 # Tekniska högskolan
#    lines: 14
#    direction: 1
#    sensor: binary_sensor.test

# Text to speech
tts:
  - platform: google # (https://www.home-assistant.io/components/tts/)

# Media player
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: mpd
    host: !secret hassio_ip

# Cloud
#cloud:

zone:
  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 150
    icon: mdi:briefcase

# Device tracker
device_tracker: !include device_tracker.yaml

# Lights
tradfri:
  host: !secret tradfri_gateway_ip

# Switches (test)
switch: !include switches.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
