homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30.25
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# HTTP
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:
  reporting: false

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Lovelace
lovelace:
  mode: yaml

# Sensors
sensor:
  # Weather prediction
  - platform: yr
    monitored_conditions:
      - symbol
      - temperature
      - humidity
      - fog
      - pressure
      - precipitation
      - windSpeed
      - cloudiness
  - platform: template
    sensors:
      yrwthr:
        value_template: '{%set list2 = "0","Clear sky","Fair","Partly cloudy","Cloudy","Rain showers","Rain showers and thunder","Sleet showers","Snow showers","Rain","Heavy rain","Heavy rain and thunder","Sleet","Snow","Snow and thunder","Fog","Sleet showers and thunder","Snow showers and thunder","Rain and thunder","Sleet and thunder","Light rain showers and thunder","Heavy rain showers and thunder","Light sleet showers and thunder","Heavy sleet showers and thunder","Light snow showers and thunder","Heavy snow showers and thunder","Light rain and thunder","Light sleet and thunder","Heavy sleet and thunder","Light snow and thunder","Heavy snow and thunder","Light rain showers","Heavy rain showers","Light sleet showers","Heavy sleet showers","Light snow showers","Heavy snow showers","Light rain","Light sleet","Heavy sleet","Light snow","Heavy snow"%}{{list2[states.sensor.yr_symbol.state|int]}}'
        entity_picture_template: "{{ state_attr('sensor.yr_symbol','entity_picture') }}"
  - platform: template
    sensors:
      device_oneplus_3:
        friendly_name: !secret name1
        value_template: >
          {{ states('device_tracker.7fcbfe5a') if is_state('device_tracker.oneplus_3','not_home') else states('device_tracker.oneplus_3') }}
      device_honor_10:
        friendly_name: !secret name2
        value_template: >
          {{ states('device_tracker.ueedu18505002624') if is_state('device_tracker.honor_104bfeb65f37112d11','not_home') else states('device_tracker.honor_104bfeb65f37112d11') }}
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: random
#  - platform: sl
#    name: home
#    ri4key: !secret trafiklab_ri4key
#    si2key: !secret trafiklab_si2key
#    siteid: 9204 # Tekniska högskolan
#    lines: 14
#    direction: 1
#    sensor: binary_sensor.test
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Text to speech
tts:
  - platform: google # (https://www.home-assistant.io/components/tts/)

# Media player
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: mpd
    host: !secret hassio_ip

# Spotify
input_number:
  spotify_volume:
    name: 'Volume:'
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
input_select:
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Morning Commute
      - Piano in the Background
      - Winnerbäck
      - Soft by Lucia
      - Akustisk Vinter
      - Cooking Music
      - Bruce
      - On Point
      - Sing-Along Indie
      - Cinematic Chill-Out
      - From a Smokey Bar
    icon: mdi:spotify
  spotify_source:
    name: 'Source:'
    options:
      - Hass.io
#      - LENNY
    initial: Hass.io
    icon: mdi:speaker-wireless

# Cloud
#cloud:

zone: !include zones.yaml

# Device tracker
device_tracker: !include device_tracker.yaml

# Lights
#tradfri:
#  host: !secret tradfri_gateway_ip

# Switches (test)
switch: !include switches.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
