homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30.25
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# HTTP
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:
  reporting: false

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Lovelace
lovelace:
  mode: yaml

# Sensors
sensor: !include sensors.yaml

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Text to speech
tts:
  - platform: google # (https://www.home-assistant.io/components/tts/)

# Media player
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: mpd
    host: !secret hassio_ip

# Spotify
input_number:
  spotify_volume:
    name: 'Volume:'
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
input_select:
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Morning Commute
      - Piano in the Background
      - Winnerbäck
      - Soft by Lucia
      - Akustisk Vinter
      - Cooking Music
      - Bruce
      - On Point
      - Sing-Along Indie
      - Cinematic Chill-Out
      - From a Smokey Bar
    icon: mdi:spotify
  spotify_source:
    name: 'Source:'
    options:
      - Hass.io
#      - LENNY
    initial: Hass.io
    icon: mdi:speaker-wireless

# Cloud
#cloud:

zone: !include zones.yaml

# Device tracker
device_tracker: !include device_tracker.yaml

# Lights
#tradfri:
#  host: !secret tradfri_gateway_ip

# Switches (test)
switch: !include switches.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
