- platform: template
  switches:
    blind:
      friendly_name: "Blind"
      value_template: "{{ is_state_attr('switch.blind_toggle', 'sensor_state', 'on') }}"
      turn_on:
        service: persistent_notification.create
        data:
          title: "A notification appeared!"
          message: "Here is a message"
          notification_id: "1235"
      turn_off:
        service: persistent_notification.dismiss
        data:
          notification_id: "1235"