title: Home Assistant

excluded_entities:
  - media_player.mpd
  # Temporary
  - switch.blind
  - automation.test_tts

background: center / cover no-repeat url("/local/field-background.jpg") fixed

views:
  - title: Home
    icon: mdi:home
    path: home
    cards:
      - type: entities
        title: Lights
        entities:
          - script.turn_on_lights
          - script.turn_off_lights
      - type: entities
        title: Spotify
        entities:
          - media_player.spotify
      - type: vertical-stack
        cards:
          - type: entity-filter
            show_empty: false
            entities:
              - device_tracker.oneplus_3
              - device_tracker.honor_104bfeb65f37112d11
              - device_tracker.7fcbfe5a
            state_filter:
              - home
            card: 
              type: glance
              title: People at home
          - type: map
            entities:
              - device_tracker.oneplus_3
              - device_tracker.honor_104bfeb65f37112d11
              - device_tracker.7fcbfe5a
              - zone.home
              - zone.work

  - title: Music
    icon: mdi:music
    path: music
    cards:
      - type: entities
        entities:
          - input_select.spotify_playlist
          - input_number.spotify_volume
          - script.spotify_music
      - type: conditional
        conditions:
        - entity: media_player.spotify
          state: "playing"
        card:
          type: media-control
          entity: media_player.spotify

  - title: Lights
    icon: mdi:lightbulb-on
    path: lights
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: section
            label: Hallway
          - entity: light.vestibule
            secondary_info: last-changed
          - entity: light.kitchen
            secondary_info: last-changed
          - type: section
            label: Living room
          - entity: light.vardagsrum
            secondary_info: last-changed
      - type: entity-filter
        show_empty: false
        entities:
          - light.vestibule
          - light.kitchen
          - light.vardagsrum
        state_filter:
          - on
        card: 
          type: glance
          show_state: false
      - type: entities
        title: Scenes
        entities:
          - scene.day
          - scene.evening
          - scene.late_evening
          - scene.night

  - title: Weather
    icon: mdi:weather-partlycloudy
    path: weather
    cards:
    - type: weather-forecast
      entity: weather.dark_sky
    - type: history-graph
      title: 'Last 24 hours'
      entities:
        - entity: sensor.yr_humidity
          name: Humidity
        - entity: sensor.yr_cloudiness
          name: Cloudiness
    - type: iframe
      url: https://embed.windy.com/embed2.html?lat=59.338&lon=18.069&zoom=11&level=surface&overlay=temperature&type=map&location=coordinates&detailLat=59.338&detailLon=18.069&metricWind=default&metricTemp=%C2%B0C&radarRange=-1
      aspect_ratio: 70%

  - title: Settings
    icon: mdi:wrench
    path: settings
    cards:
      - type: entities
        title: Automations
        entities:
          - type: section
            label: Come-and-go
          - automation.enter
          - automation.exit
          - type: section
            label: Lights
          - automation.sunset_lights
          - automation.evening_lights
          - automation.late_evening_lights
          - automation.turn_off_lights
      - type: entities
        title: Links
        entities:
          - type: weblink
            url: !secret router_url
            icon: mdi:router-wireless
            name: Router
          - type: weblink
            url: !secret ide_url
            icon: mdi:code-braces
            name: IDE
          - type: weblink
            url: !secret shopping_list_url
            icon: mdi:wunderlist
            name: Shopping list
