title: Home Assistant

excluded_entities:
  - media_player.mpd
  # Temporary
  - switch.blind
  - automation.test_tts

background: center / cover no-repeat url("/local/background.png") fixed

views:
  - title: Home
    icon: mdi:home
    path: home
    cards:
      - type: markdown
        title: Welcome
        content: >
          What can I do for you?
      - type: entities
        title: Lights
        entities:
          - script.turn_on_lights
          - script.turn_off_lights
      - type: entities
        title: Spotify
        entities:
          - media_player.spotify

  - title: Music
    icon: mdi:music
    path: music
    cards:
      - type: entities
        entities:
          - input_select.spotify_playlist
          - input_select.spotify_source
          - input_number.spotify_volume
          - script.spotify_music
      - type: media-control
        title: Spotify
        entity: media_player.spotify


  - title: Lights
    icon: mdi:lightbulb-on
    path: lights
    cards:
      - type: entities
        title: Lights
        entities:
          - light.farstun
          - light.koket
          - light.vardagsrum
      - type: entities
        title: Scenes
        entities:
          - scene.day
          - scene.evening
          - scene.late_evening
          - scene.night

  - title: Map
    icon: mdi:map
    panel: true
    cards:
    - type: map
      entities:
        - device_tracker.oneplus_3
        - device_tracker.honor_104bfeb65f37112d11
        - zone.home
        - zone.work

  - title: Settings
    icon: mdi:wrench
    path: settings
    cards:
      - type: entities
        title: Automations
        entities:
          - automation.enter_lights
          - automation.exit_lights
          - automation.test_notification
